services:
    h1bot:
        image: elfensky/h1bot:latest
        container_name: h1bot # Optional: name your container
        environment:
            - DATABASE_URL=${DATABASE_URL} #mysql database
            - SENTRY_DSN=${SENTRY_DSN} #sentry.io
            - TOKEN=${TOKEN} #discord access token
            - CLIENT_ID=${CLIENT_ID} #application id
            - GUILD_ID=${GUILD_ID} #discord server id, this is lavrenov.io
            - CHANNEL_ID=${CHANNEL_ID} #chat channel
        restart: unless-stopped
        network_mode: bridge # Use the default, ufw-whitelisted Docker Network
        extra_hosts:
            - 'host.docker.internal:host-gateway' # pass the host to container, required on linux
